### ISSUE TITLE
ui enhancements

### ISSUE THREAD

**Issue by RohithChittibommala** [Club-Collabaration/club-collaboration-frontend#9] opened 2020-08-31 06:46 UTC
I would like to add UI enhancements (add hover, transition effects )

**Comment by RohithChittibommala** [comment] 2020-08-31 06:48
I would like to work on this issue

**Comment by RohithChittibommala** [comment] 2020-08-31 08:26
@iiitv/project-maintainers  I would like to add UI enhancements, please let me know whether I can work on this issue or not

**Comment by theyashshahs** [comment] 2020-08-31 16:21
@RohithChittibommala what will you contribute to in this issue

**Comment by RohithChittibommala** [comment] 2020-08-31 17:46
hover effects on  links  main logo   club logos            On Aug 31, 2020 9:52 PM, Yash Shah <notifications@github.com> wrote:
@RohithChittibommala what will you contribute to in this issue

**Comment by RohithChittibommala** [comment] 2020-08-31 17:50
I also want to work on the following issuesWhen the user clicks on the nav links ( say announcement link) Page is blank I think it would be if we provide a message to user about page instead blank pageI also want to modify form On Aug 31, 2020 11:16 PM, myselfrohith@outlook.com wrote: hover effects on  links  main logo   club logos            On Aug 31, 2020 9:52 PM, Yash Shah <notifications@github.com> wrote:
@RohithChittibommala what will you contribute to in this issue

**Comment by theyashshahs** [comment] 2020-09-20 09:57
@RohithChittibommala please do not create a PR unless the issue is assigned to you

**Closed as completed** 2020-09-24 08:00 UTC
